azure:
  tenantid: d84794ee-9e36-4e44-8841-96cc6abea252

spring:
  security:
    oauth2:
      client:
        provider:
          azure-ad:
            authorization-uri: https://login.microsoftonline.com/${azure.tenantid}/oauth2/v2.0/authorize
            user-info-uri: https://graph.microsoft.com/oidc/userinfo 
            token-uri: https://login.microsoftonline.com/${azure.tenantid}/oauth2/v2.0/token
            jwk-set-uri: https://login.microsoftonline.com/${azure.tenantid}/v2.0/keys
            user-name-attribute: name
            user-info-authentication-method: "header"
        registration:
          azure-client:
            provider: azure-ad
            client-id: 26ef781f-53df-47a7-a009-dc338ad3dfb2
            client-secret: f6111a31-5281-420b-ae89-135f3d82d0c7
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid, email, profile
            client-authentication-method: post
server:
  forward-headers-strategy: native
  
  