azure:
  tenantid: d84794ee-9e36-4e44-8841-96cc6abea252

spring:
  security:
    oauth2:
      client:
        provider:
          azure-ad:
            authorization-uri: https://login.microsoftonline.com/${azure.tenantid}/oauth2/v2.0/authorize
            user-info-uri: https://graph.microsoft.com/oidc/userinfo 
            token-uri: https://login.microsoftonline.com/${azure.tenantid}/oauth2/v2.0/token
            jwk-set-uri: https://login.microsoftonline.com/${azure.tenantid}/v2.0/keys
            user-name-attribute: name
            user-info-authentication-method: "header"
        registration:
          azure-client:
            provider: azure-ad
            client-id: 8db14fbd-165d-4326-b8db-432653548fec
            client-secret: WCN8Q~_4Lsjtpb314mxqEyDOiyl9PqKMZIODwce7
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid, https://tdpsynopsis.onmicrosoft.com/ec5845d9-1d86-4da3-aecc-ed981b1d1dcb/Read
            client-authentication-method: post
server:
  forward-headers-strategy: native
  
  